name: Performing github actions

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types:
            - opened
            - closed
    workflow_dispatch:
jobs:
    Testjob:
        runs-on: ubuntu-latest
        steps:
            - name: get the code
              uses: actions/checkout@v3
            - name: set the env
              uses: actions/setup-node@v3
              with:
                    node-version: '14'
            - name: Dependency caching
              uses: actions/cache@v3
              with:
                     path: ~/.npm
                     key: ${{ runner.os }}-dep-cache-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci 
            - name: Perform linting
              run: npm run lint
            - name: Perform Testing
              run: npm run test
            - name: upload the test report
              uses: actions/upload-artifact@v3
              with:
                     name: test-report
                     path: test.json
                     